dev:
  config:
    data:
      UNISWAP_V2_DATA_PATH: "data/data_uniswap_v2"
      UNISWAP_V3_DATA_PATH: "data/data_uniswap_v3"
      COMPOUND_DATA_PATH: "data/data_compound"
      AAVE_DATA_PATH: "data/data_aave"
      GLOBAL_DATA_PATH: "data/data_global"
      NETWORK_DATA_PATH: "data/data_network"
      BETWEENNESS_DATA_PATH: "data/data_betweenness"
    result:
      FIGURE_PATH: "figures"
      TABLE_PATH: "tables"
    moving_average_plot:
      KEY_TOKEN_LIST: ["WETH", "WBTC", "MATIC", "USDC", "USDT", "DAI", "FEI"]
      EVENT_DATE_LIST: ["2020-11-26", "2021-05-05", "2022-05-10", "2022-11-11"]
    compound:
      "ETH": "0x4ddc2d193948926d02f9b1fe9e1daa0718270ed5"
      "USDC": "0x39aa39c021dfbae8fac545936693ac917d5e7563"
      "USDT": "0xf650c3d88d12db855b8bf7d11be6c55a4e07dcc9"
      "WBTC": "0xc11b1268c1a384e55c48c2391d8d480264a3a7f4"
      "DAI": "0x5d3a536e4d6dbd6114cc1ead35777bab948e3643"
      "UNI": "0x35a18000230da775cac24873d00ff85bccded550"
      "SAI": "0xf5dce57282a584d2746faf1593d3121fcac444dc"
      "REP": "0x158079ee67fce2f58472a96584a73c7ab9ac95c1"
      "MKR": "0x95b4ef2869ebd94beb4eee400a99824bf5dc325b"
      "YFI": "0x80a2ae356fc9ef4305676f7a3e2ed04e12c33946"
      "USDP": "0x041171993284df560249b57358f931d9eb7b925d"
      "ZRX": "0xb3319f5d18bc0d84dd1b4825dcde5d5f7266d407"
      "SUSHI": "0x4b0181102a0112a2ef11abee5563bb4a3176c9d7"
      "FEI": "0x7713dd9ca933848f6819f38b8352d9a15ea73f67"
      "BAT": "0x6c8c6b02e7b2be14d4fa6022dfd6d75921d90e4e"
      "COMP": "0x70e36f6bf80a52b3b46b3af8e106cc0ed743e8e4"
      "TUSD": "0x12392f67bdf24fae0af363c24ac620a2f67dad86"
      "AAVE": "0xe65cdb6479bac1e22340e4e755fae7e509ecd06c"
      "LINK": "0xface851a4921ce59e912d19329929ce6da6eb0c7"
    aave:
      DUNE_ACCOUNT: "hileoo"
      DUNE_PASSWORD: "QWERtyui123"
    coingecko:
      START_DATE: "2019-01-01"
      END_DATE: "2023-02-01"
    dynamic:
      HEIGHT: 1600
      WIDTH: 1200
    subgraph:
      HTTP_V2: "https://api.thegraph.com/subgraphs/name/uniswap/uniswap-v2"
      HTTP_V3: "https://api.thegraph.com/subgraphs/name/uniswap/uniswap-v3"
    token_library:
      v2:
        token: ['WETH',
                'USDC',
                'APE',
                'ELON',
                'USDT',
                'CULT',
                'FNK',
                'SAND',
                'FEI',
                'VADER',
                'KUMA',
                'X2Y2',
                'SAITAMA',
                'MC',
                'STARL',
                'FUSE',
                'TORN',
                'MANA',
                'CAW',
                'HEX',
                'FLOKI',
                'WOO',
                'STRONG',
                'DAI',
                'SUPER',
                'UFO',
                'AMPL',
                'WILD',
                'HIGH',
                'FLX',
                'CRV',
                'TOKE',
                'TEND',
                'ZCX',
                'LEASH',
                'DPX',
                'KOKO',
                'XMON',
                'SHIB',
                'BOND',
                'WRLD',
                'QOM',
                'AUDIO',
                'GALA',
                'UNI',
                'SHINJA',
                'LINK',
                'WBTC',
                'LOOKS',
                'REEF',
                'KISHU',
                'Mononoke-Inu',
                'eRSDL',
                'xFUND',
                'PAID',
                'AMP',
                'MRI',
                'PAXG',
                'ShibDoge',
                'ICE',
                'MCC',
                'AKITA',
                'BEAN',
                'SMI',
                'NTVRK',
                'RAD',
                'OCT',
                'CELL',
                'DEPO',
                'MATIC',
                'RBN',
                'PERP',
                'GTC',
                'SAITO',
                'GM',
                'Metis',
                'DG',
                'MPL',
                'PUSH',
                'FRAX',
                'eMax',
                'RGT',
                'LUNA',
                'FARM',
                'AAVE',
                '___',
                'ERN',
                'ETH2x-FLI',
                'CGG',
                'REFI',
                'VOLT',
                'CARDS',
                'ALBT',
                'DAO',
                'KEEP',
                'RAI',
                'MOOV',
                'DOP',
                'WOOL',
                'POLC',
                'TERA',
                'LGCY',
                'SIDUS',
                'GERO',
                'WDOGE',
                'REQ',
                'DEFIT',
                'JEJUDOGE',
                'COTI',
                'TVK',
                'DERC',
                'GLCH',
                'stETH',
                'C3',
                '10SET',
                'FEG',
                'RLY',
                'STAKE',
                'AVG',
                'FTM',
                'COMP',
                'DEXT',
                'FOX',
                'PYR',
                'WAXE',
                'MKR',
                'KLEE',
                'FEAR',
                'RACA',
                'CVP',
                'DPI',
                'IMPACTXP',
                'KIBA',
                'BOBA',
                'ACYC',
                'STRNGR',
                'eXRD',
                'CHEDDA',
                'TRU',
                'DBUY',
                'VEMP',
                'POLS',
                'VPAD',
                '$AKC',
                'DXO',
                'ARC',
                'UFT',
                'VISR',
                'MUTE',
                'TKING',
                'MCHC',
                'EJS',
                'STAK',
                'FXS',
                'PDT',
                'BOOST',
                'F9',
                'BEND',
                'UPI',
                'BFC',
                'XCAD',
                'FOXX',
                'ASTO',
                'POCHI',
                'SHINTAMA',
                'ALI',
                'CUMINU',
                'GRO',
                'wPE',
                'YFI',
                'SUSHI',
                'WISE',
                'LDO',
                'sUSD',
                'DSD',
                'ESD',
                'LUSD']
        stable: [ 0,
                  1,
                  0,
                  0,
                  1,
                  0,
                  0,
                  0,
                  1,
                  0,
                  0,
                  0,
                  0,
                  0,
                  0,
                  0,
                  0,
                  0,
                  0,
                  0,
                  0,
                  0,
                  0,
                  1,
                  0,
                  0,
                  0,
                  0,
                  0,
                  0,
                  0,
                  0,
                  0,
                  0,
                  0,
                  0,
                  0,
                  0,
                  0,
                  0,
                  0,
                  0,
                  0,
                  0,
                  0,
                  0,
                  0,
                  0,
                  0,
                  0,
                  0,
                  0,
                  0,
                  0,
                  0,
                  0,
                  0,
                  0,
                  0,
                  0,
                  0,
                  0,
                  0,
                  0,
                  0,
                  0,
                  0,
                  0,
                  0,
                  0,
                  0,
                  0,
                  0,
                  0,
                  0,
                  0,
                  0,
                  0,
                  0,
                  1,
                  0,
                  0,
                  0,
                  0,
                  0,
                  0,
                  0,
                  0,
                  0,
                  0,
                  0,
                  0,
                  0,
                  0,
                  0,
                  0,
                  0,
                  0,
                  0,
                  0,
                  0,
                  0,
                  0,
                  0,
                  0,
                  0,
                  0,
                  0,
                  0,
                  0,
                  0,
                  0,
                  0,
                  0,
                  0,
                  0,
                  0,
                  0,
                  0,
                  0,
                  0,
                  0,
                  0,
                  0,
                  0,
                  0,
                  0,
                  0,
                  0,
                  0,
                  0,
                  0,
                  0,
                  0,
                  0,
                  0,
                  0,
                  0,
                  0,
                  0,
                  0,
                  0,
                  0,
                  0,
                  0,
                  0,
                  0,
                  0,
                  0,
                  0,
                  0,
                  0,
                  0,
                  0,
                  0,
                  0,
                  0,
                  0,
                  0,
                  0,
                  0,
                  0,
                  0,
                  0,
                  0,
                  0,
                  0,
                  0,
                  0,
                  0,
                  0,
                  0,
                  0,
                  1,
                  1,
                  1,
                  1]
      v3:
        token: ['WETH',
                'USDC',
                'APE',
                'USDT',
                'DAI',
                'WBTC',
                'UST',
                'LOOKS',
                'FEI',
                'UNI',
                'AXS',
                'Metis',
                'XSGD',
                'LINK',
                'HEX',
                'SHIB',
                'NEXO',
                'MM',
                'COMP',
                'MATIC',
                'ETH2x-FLI',
                'SLP',
                'MIM',
                'FRAX',
                'NCR',
                'EURS',
                'PERP',
                'FTM',
                'EURT',
                'OHM',
                'RAI',
                'STRONG',
                'GALA',
                'ICE',
                'ENS',
                'LEASH',
                'DYDX',
                'CRV',
                'agEUR',
                'RBN',
                'AAVE',
                'SPELL',
                'SAND',
                'PAX',
                'VXV',
                'LCX',
                'TKING',
                'MKR',
                'TRU',
                'GNO',
                'YGG',
                'sILV2',
                'RARE',
                'UBT',
                'WRLD',
                'QNT',
                'MANA',
                'RUNE',
                'Nvir',
                'oneUNI',
                'LYXe',
                'CEL',
                'BTRFLY',
                'IMX',
                'LUSD',
                'BYTES',
                'PEOPLE',
                'TRIBE',
                'sUSD',
                'DPI',
                'RPL',
                'INST',
                'LUNA',
                'GTC',
                'FXS',
                '1INCH',
                'AGLD',
                'OGN',
                'FX',
                'CVX',
                'oSQTH',
                'FLOOR',
                'WOOL',
                'WOO',
                'wstETH',
                'YFI',
                'UNQT',
                'SUSHI',
                'MCB',
                'TUSD',
                'ENJ',
                'gOHM',
                'HDRN',
                'renBTC',
                'FTX Token',
                'rETH',
                'WTON',
                'ERN',
                'XYO',
                'STG',
                'PILOT',
                'BUSD',
                'wNXM',
                'SHI',
                'CNV',
                'aKLIMA',
                'BAT',
                'WDOGE']
        stable: [ 0,
                  1,
                  0,
                  1,
                  1,
                  0,
                  1,
                  0,
                  1,
                  0,
                  0,
                  0,
                  1,
                  0,
                  0,
                  0,
                  0,
                  0,
                  0,
                  0,
                  0,
                  0,
                  1,
                  1,
                  0,
                  1,
                  0,
                  0,
                  1,
                  0,
                  0,
                  0,
                  0,
                  0,
                  0,
                  0,
                  0,
                  0,
                  1,
                  0,
                  0,
                  0,
                  0,
                  1,
                  0,
                  0,
                  0,
                  0,
                  0,
                  0,
                  0,
                  0,
                  0,
                  0,
                  0,
                  0,
                  0,
                  0,
                  0,
                  1,
                  0,
                  0,
                  0,
                  0,
                  1,
                  0,
                  0,
                  0,
                  1,
                  0,
                  0,
                  0,
                  0,
                  0,
                  0,
                  0,
                  0,
                  0,
                  0,
                  0,
                  0,
                  0,
                  0,
                  0,
                  0,
                  0,
                  0,
                  0,
                  0,
                  1,
                  0,
                  0,
                  0,
                  0,
                  0,
                  0,
                  0,
                  0,
                  0,
                  0,
                  0,
                  1,
                  0,
                  0,
                  0,
                  0,
                  0,
                  0]